name: GitHub Actions Continuous Integration

# 1. Configurar disparador para Pull Requests dirigidos a la rama principal (master o main)
on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 2. Descargar el código del repositorio
      - name: Checkout Code
        uses: actions/checkout@v4

      # 3. Configurar el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      # 4. Instalar las dependencias del proyecto y de calidad de código
      - name: Install Dependencies
        run: |
          python -m pip upgrade pip
          pip install pylint pytest pytest-json-report flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 5. Ejecutar Linting automático (Enfoque principal requerido por el taller)
      - name: Analyzing code with pylint
        run: |
          pylint $(git ls-files '*.py')

      # 6. Opcional: Ejecutar pruebas unitarias para asegurar que los requerimientos no fallen
      - name: Run Unit Tests with Pytest
        run: |
          pytest
